name: apache-wayang

services:
  app:
    container_name: apache-wayang-app
    image: apache/incubator-wayang:latest
    # For apple-silicon
    #image: apache/incubator-wayang:0.7.1-arm64
    ports:
      - 8888:8888
    volumes:
      - ./:/var/www/html
      - ./.m2/repository/:/root/.m2/repository
    tty: true
    restart: always
